#!/bin/sh
set -e

## From the environment variables replace the nginx configuration placeholders
ESCAPE='$' envsubst < /var/www/storage/nginx/conf/vhost.conf.template > /etc/nginx/conf.d/default.conf
ESCAPE='$' envsubst < /var/www/storage/nginx/conf/nginx.conf.template > /etc/nginx/nginx.conf
ESCAPE='$' envsubst < /var/www/storage/nginx/conf/cors.conf.template > /etc/nginx/location.d-available/cors.conf

if [ "$NGINX_CORS_ENABLE" = true ]; then
    docker-nginx-location.d-enable cors
fi

exec nginx -g 'daemon off;'
